# Generated by Django 4.0.5 on 2022-07-21 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nok_web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='rating',
        ),
    ]
