# Generated by Django 4.0.5 on 2022-07-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nok_web', '0002_remove_books_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='google_docs_file',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Гугл документ же китеп'),
        ),
    ]
