# Generated by Django 4.0.5 on 2022-07-23 15:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nok_web', '0003_books_google_docs_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_video_file',
            field=models.FileField(blank=True, null=True, upload_to='video_posts/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])], verbose_name='Иш чаранын видеосу'),
        ),
    ]
