# Generated by Django 4.0.5 on 2022-07-24 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nok_web', '0004_post_post_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='youtube_links',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Иш чаранын ютуб каналдагы шилтемеси'),
        ),
    ]
