# Generated by Django 4.0.5 on 2022-07-25 05:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nok_web', '0006_post_facebook_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='facebook_links',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Иш чаранын фейсбук каналдагы шилтемеси'),
        ),
        migrations.AddField(
            model_name='news',
            name='post_video_file',
            field=models.FileField(blank=True, null=True, upload_to='video_news/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])], verbose_name='Иш чаранын видеосу'),
        ),
        migrations.AddField(
            model_name='news',
            name='youtube_links',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Иш чаранын ютуб каналдагы шилтемеси'),
        ),
    ]
