# Generated by Django 4.0.5 on 2022-07-25 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nok_web', '0007_news_facebook_links_news_post_video_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='post_video_file',
            new_name='news_video_file',
        ),
    ]
