# Generated by Django 4.0.5 on 2022-07-26 09:04

from django.db import migrations, models
import django.db.models.deletion
import nok_web.models


class Migration(migrations.Migration):

    dependencies = [
        ('nok_web', '0008_rename_post_video_file_news_news_video_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images_News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=nok_web.models.get_image_filename, verbose_name='Image')),
                ('news', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='nok_web.news')),
            ],
        ),
    ]
