# Generated by Django 4.0.5 on 2022-07-26 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nok_web', '0009_images_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author_news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='автор публикации'),
        ),
    ]
