# Generated by Django 4.0.5 on 2022-07-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nok_web', '0011_images_news_description_images_news_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images_news',
            name='description',
            field=models.CharField(blank=True, default=' ', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='images_news',
            name='title',
            field=models.CharField(blank=True, default=' ', max_length=200, null=True, verbose_name='Слайдга кыскача тема'),
        ),
    ]
