# Generated by Django 4.0.5 on 2022-07-27 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import nok_web.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nok_web', '0012_alter_images_news_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_posts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='автор публикации'),
        ),
        migrations.CreateModel(
            name='Images_Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Слайдга кыскача тема')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to=nok_web.models.get_image_filename, verbose_name='Image')),
                ('posts', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='posts_slides_img', to='nok_web.post')),
            ],
        ),
    ]
